adding new release

diff --git a/stable/proxysql/templates/configmap/configuration.yaml b/stable/proxysql/templates/configmap/configuration.yaml
--- a/stable/proxysql/templates/configmap/configuration.yaml
+++ b/stable/proxysql/templates/configmap/configuration.yaml
@@ -37,7 +37,7 @@ data:
       interfaces="0.0.0.0:6033"
       default_schema="information_schema"
       stacksize=1048576
-      server_version="8.0.20"
+      server_version="21c"
       connect_timeout_server=3000
       monitor_username="monitor"
       monitor_password="monitor"
@@ -60,69 +60,93 @@ data:
       { username = "{{ $e.username }}" , password = "{{ $e.password }}" , default_hostgroup = 0 , active = 1 },
       {{- end}}
 
-       { username = "{{ $.Values.proxysql.mysql.monitoring.username }}" , password = "{{ $.Values.proxysql.mysql.monitoring.password }}" , default_hostgroup = 0 , active = 1 }
+     
     )
 
+    proxysql_servers =
+    (
+      {{ range $i, $e := until $replicas }}
+      {
+        hostname="{{ $fullname }}-{{ $e }}.{{ $fullname }}-headless"
+        port=6032
+        weight={{ $i }}
+        comment="{{ $fullname }}-{{ $e }}.{{ $fullname }}"
+      }{{ if lt $i (sub $replicas 1) }},{{ end }}
+      {{ end }}
+    )
 
     {{ .Values.proxysql.customConfiguration | default "" | nindent 4 }}
 
+    scheduler=
+    (
+      {
+        id=1
+        active=1
+        interval_ms=5000
+        filename="/bin/bash"
+        arg1="/usr/local/sbin/config-watcher.sh"
+        arg2=""
+        arg3=""
+        arg4=""
+        arg5=""
+      }
+    )
 
+  readiness.sh: |
+    #!/bin/bash
+    set -e
 
-  # readiness.sh: |
-  #   #!/bin/bash
-  #   set -e
+    # this needs to be smarter. It should be able to tell if the container is running
+    # and accepting traffic
+    if [ ! -f /var/lib/proxysql/.running ]; then
+      exit 1
+    fi
+    exit 0
 
-  #   # this needs to be smarter. It should be able to tell if the container is running
-  #   # and accepting traffic
-  #   if [ ! -f /var/lib/proxysql/.running ]; then
-  #     exit 1
-  #   fi
-  #   exit 0
+  liveness.sh: |
+    #!/bin/bash
+    set -e
 
-  # liveness.sh: |
-  #   #!/bin/bash
-  #   set -e
+    mbin="/usr/bin/mysql"
+    lcon="-h127.0.0.1 -P6032 -uadmin -p{{ .Values.proxysql.admin.adminPassword }}"
+    opts="-NB"
 
-  #   mbin="/usr/bin/mysql"
-  #   lcon="-h127.0.0.1 -P6032 -uadmin -p{{ .Values.proxysql.admin.adminPassword }}"
-  #   opts="-NB"
-
-  #   proxysql_peers_available=$($mbin $lcon $opts -e"select count(*) from runtime_proxysql_servers")
+    proxysql_peers_available=$($mbin $lcon $opts -e"select count(*) from runtime_proxysql_servers")
   
-  #   if [[ $proxysql_peers_available -eq {{ $replicas }} ]];
-  #   then
-  #     echo "ProxySQL peers configured"
-  #     exit 0
-  #   else
-  #     echo "ProxySQL peers not yet configured or failed"
-  #     exit 1
-  #   fi
+    if [[ $proxysql_peers_available -eq {{ $replicas }} ]];
+    then
+      echo "ProxySQL peers configured"
+      exit 0
+    else
+      echo "ProxySQL peers not yet configured or failed"
+      exit 1
+    fi
 
-  # drain.sh: |
-  #   #!/bin/bash
-  #   CONNECTIONS=$(mysqladmin processlist -P6032 -h127.0.0.1 -uadmin -p{{ .Values.proxysql.admin.adminPassword }} | grep [0-9] -c)
-  #   echo "${CONNECTIONS}"
+  drain.sh: |
+    #!/bin/bash
+    CONNECTIONS=$(mysqladmin processlist -P6032 -h127.0.0.1 -uadmin -p{{ .Values.proxysql.admin.adminPassword }} | grep [0-9] -c)
+    echo "${CONNECTIONS}"
 
-  #   while [[ ${CONNECTIONS} -gt 0 ]]; do
-  #     sleep 5
-  #     CONNECTIONS=$(mysqladmin processlist -P6032 -h127.0.0.1 -uadmin -p{{ .Values.proxysql.admin.adminPassword }} | grep [0-9] -c)
-  #     echo "${CONNECTIONS}"
+    while [[ ${CONNECTIONS} -gt 0 ]]; do
+      sleep 5
+      CONNECTIONS=$(mysqladmin processlist -P6032 -h127.0.0.1 -uadmin -p{{ .Values.proxysql.admin.adminPassword }} | grep [0-9] -c)
+      echo "${CONNECTIONS}"
     
-  #   done
+    done
 
-  #   exit 0
+    exit 0
 
-  # config-watcher.sh: |
-  #   #!/bin/bash
+  config-watcher.sh: |
+    #!/bin/bash
 
-  #   if [ ! -f /var/lib/proxysql/.running ]; then
-  #     /usr/bin/mysql -uadmin -p{{ .Values.proxysql.admin.adminPassword }} -h127.0.0.1 -P6032 -e"
-  #       LOAD MYSQL QUERY RULES TO RUNTIME;
-  #       LOAD MYSQL SERVERS TO RUNTIME;
-  #       LOAD MYSQL USERS TO RUNTIME;
-  #     "
-  #     touch /var/lib/proxysql/.running
-  #   fi
+    if [ ! -f /var/lib/proxysql/.running ]; then
+      /usr/bin/mysql -uadmin -p{{ .Values.proxysql.admin.adminPassword }} -h127.0.0.1 -P6032 -e"
+        LOAD MYSQL QUERY RULES TO RUNTIME;
+        LOAD MYSQL SERVERS TO RUNTIME;
+        LOAD MYSQL USERS TO RUNTIME;
+      "
+      touch /var/lib/proxysql/.running
+    fi
 
-  #   exit 0
+    exit 0
 
